"""Контрольная 4

Revision ID: 870ceceb827d
Revises: e57977cf096e
Create Date: 2025-01-10 16:49:26.820937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '870ceceb827d'
down_revision = 'e57977cf096e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('avatar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_message', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('avatar', schema=None) as batch_op:
        batch_op.drop_column('first_message')

    # ### end Alembic commands ###
