"""Контрольная 5

Revision ID: cdc39ad8e3fa
Revises: 870ceceb827d
Create Date: 2025-01-10 17:03:41.013683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdc39ad8e3fa'
down_revision = '870ceceb827d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('avatar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_or_position', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('avatar', schema=None) as batch_op:
        batch_op.drop_column('role_or_position')

    # ### end Alembic commands ###
